name: Generate UML Diagram

on:
  push:
    branches: [ main ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.3'

      - name: Install code_uml globally
        run: dart pub global activate code_uml

      - name: Generate UML .puml files
        run: |
          dart pub global run code_uml --from=$(pwd)/lib --to=uml_output --uml=plantuml

      - name: Install PlantUML
        run: sudo apt-get update && sudo apt-get install -y plantuml

      - name: Generate PNG UML diagrams
        run: |
          mkdir -p uml_png
          plantuml -tpng uml_output/*.puml -o ../uml_png

      - name: Upload UML diagram images
        uses: actions/upload-artifact@v4
        with:
          name: UML-Diagrams
          path: uml_png
