name: Generate UML Diagram

on:
  push:
    branches: [ main ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.3.0'

      - name: Install code_uml
        run: dart pub global activate code_uml

      - name: Generate UML
        run: code_uml --from=lib --to=uml_output --uml=plantuml

      - name: Upload UML diagram as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UML-Diagram
          path: uml_output/
