name: Generate UML Diagram

on:
  push:
    branches: [ main ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # Replace with your version if needed

      - name: Install dependencies
        run: flutter pub get

      - name: Generate UML
        run: dart run dart_uml:generate --output-dir=uml_output

      - name: Upload UML diagram as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UML-Diagram
          path: uml_output/
